Feature/header#12
rafael-g-depaulo/labfaz pull request #21
Opened 2021-06-10 22:48 UTC by priscila-eng

Implementa componentes header e banner sem identidade visual.

2021-06-15 21:42 UTC, rafael-g-depaulo commented
precisa descomentar src/Api/index.ts
precisa substituir <a> por <Link>
os espaçamentos do Header não estão legais em tamanhos diferentes de tela

2021-06-16 22:11 UTC, rafael-g-depaulo commented on apps/client/src/Components/Header/style.ts
> -    width: 1px;
eu não acho que precisava mudar esse width. coisas de tamanho 1px normalmente ficam melhor assim mesmo que usando outras unidades. mas tá suave como 0.07rem tbm, não precisa mudar de volta

2021-06-16 22:33 UTC, rafael-g-depaulo requested changes
tá incrível, quase perfeito. só gostaria de resolver esses detalhes que eu considero importantes para a experiência final do usuário

2021-06-16 22:33 UTC, rafael-g-depaulo commented on apps/client/src/Components/Header/style.ts
![image](https://user-images.githubusercontent.com/31452686/122302827-04e0d280-ced9-11eb-89aa-ce15153f06b3.png)
![image](https://user-images.githubusercontent.com/31452686/122302834-090cf000-ced9-11eb-9f91-2b5062e52cd3.png)

a borda do link tá colada com o texto. tem como você fazer o link crescer pra capturar o mouse? eu imagino que a melhor solução para isso seja com uma estilização do Link usando flex-grow e flex-gap. algo como isso:

```typescript
const NavLink = styled(Link)`
  ${Navbar} & {
    flex-grow: 1;
  }
`
// e com flex-gap no Navbar
```

2021-06-16 22:33 UTC, rafael-g-depaulo commented on apps/client/src/Components/Header/style.ts
![image](https://user-images.githubusercontent.com/31452686/122303173-7caefd00-ced9-11eb-977e-ddace14e9f52.png)
![image](https://user-images.githubusercontent.com/31452686/122303180-80428400-ced9-11eb-8a3e-6dc25c96a1d9.png)

aí efetivamente a gente faria essa área azul-clara do navlink expandir, em vez de espaçar eles com o espaço roxo vazio que é o space-around que está sendo usado (ainda pode mantes space-around, só acho legal a gente crescer os links para facilitar a UX do usuário)

2021-06-19 18:52 UTC, priscila-eng commented on apps/client/src/Components/Header/style.ts
Header: adicionei visão mobile e alterei o hitbox dos links

Banner: adaptei para receber props

client/.storybook/preview.js: comentei linhas relacionado ao theme, como não tem mais no projeto, tava dando erro no storybook.

2021-06-21 13:47 UTC, closed without merging