Feature/backers#18
rafael-g-depaulo/labfaz pull request #24
Opened 2021-06-15 14:11 UTC by priscila-eng

2021-06-15 23:36 UTC, rafael-g-depaulo requested changes

2021-06-15 23:36 UTC, rafael-g-depaulo commented on apps/client/src/Components/Partners/Logo/style.ts
> +  width: 6rem;
adicionar um `object-fit` aqui é bom pra posicionar a imagem dentro da sua caixa

2021-06-16 20:08 UTC, priscila-eng commented on apps/client/src/Components/Partners/Logo/style.ts
> +  width: 6rem;
Adicionei essa props

2021-06-16 20:24 UTC, rafael-g-depaulo approved these changes
tudo certo!

2021-06-16 22:53 UTC, merged