[WIP]Feature/quem somos
rafael-g-depaulo/labfaz pull request #35
Opened 2021-06-20 21:41 UTC by Zipudhe

Cria os componentes de apresentação previstos no [prototype](https://www.figma.com/proto/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=239%3A76&scaling=scale-down&page-id=0%3A1) utilizando dados vindo da API.

2021-06-29 01:26 UTC, Jaxiii approved these changes
Nice

2021-06-29 03:14 UTC, rafael-g-depaulo requested changes

2021-06-29 03:14 UTC, rafael-g-depaulo commented on apps/client/src/Components/Text/style.ts
> +  height?: string,
height e width de um container devem ser definidas de forma dinâmica a partir do tamanho dos seus filhos. de qualquer forma essas props não estão sendo usadas pra nada até agora? eu estou bem confuso com a definição desses tipos 
DivProps e ParagraphProps sendo que essas props não estão sendo usadas. isso é resquício de código antigo que não foi removido?

2021-06-29 03:14 UTC, rafael-g-depaulo commented on apps/client/src/Components/Text/style.ts
> +      font-size: 14px;
font-size e line-height devem ser definidas com variáveis de css. é uma boa prática também preceder strings como essa com a função template "css". exemplo:

```typescript
import { css } from "styled-components"

const Paragraph = styled.p`
  ${mobileOnly(css`
    font-size: var(--font-size-mobile);
  `)}
`

```

2021-06-29 03:14 UTC, rafael-g-depaulo commented on apps/client/src/Routes/AboutUs/AboutUsPage/BannerComponent/index.tsx
> +export const Banner: FC<BannerProps> = ({ subtitle }) => {
já existe um componente Banner na develop. dê rebase nela e use ele em vez de re-implementar ele aqui

2021-06-29 03:14 UTC, rafael-g-depaulo commented on apps/client/src/Routes/index.tsx
> +        <Route path={["/aboutUs", "/about-us", "/AboutUs", "/About-us", "/About-Us"]}>
a rota é case insensitive, então /aboutUs e /aboutus são a mesma rota. as rotas tem que ter opções em português também. na verdade, devemos pensar nas rotas primeiramente em português, já que essas são as formas mais fáceis para os nossos usuários lerem e interpretarem as rotas. recomendo adicionar pelo menos um "/sobre-nos", "/sobre", "/about"

2021-06-30 00:06 UTC, rafael-g-depaulo requested changes

2021-06-30 00:06 UTC, rafael-g-depaulo commented on apps/client/src/Routes/AboutUs/AboutUsPage/styles.ts
> +  height: 80vh;
recomendo não settar heights de containers, mas sim deixar que o conteúdo deles (os filhos) ditem dinamicamente o seu tamanho

2021-06-30 00:06 UTC, rafael-g-depaulo commented on apps/client/src/Routes/AboutUs/AboutUsPage/styles.ts
> +  background-color: #C4C4C4;
cores devem ser settadas por meio de css vars

2021-06-30 00:06 UTC, rafael-g-depaulo commented on apps/client/src/Routes/AboutUs/AboutUsPage/styles.ts
> +    font-size: 48px;
font size deve ser settada por meio de css vars

2021-06-30 00:06 UTC, rafael-g-depaulo commented on apps/client/src/Routes/AboutUs/AboutUsPage/styles.ts
> +      font-size: 40px
font size deve ser settada por meio de css vars

2021-07-01 00:19 UTC, rafael-g-depaulo requested changes
quase perfeito. só mais 2 coisinhas e já dá pra juntar

2021-07-01 00:19 UTC, rafael-g-depaulo commented on apps/client/src/Api/AboutUs.ts
> +  .then(({ data }) => data[0])
se a gente só vai pegar o primeiro, faz mais sentido ter o "/about-uses" como single type em vez de colection, não? também faz mais sentido pra mim no geral que isso seria um single em vez de uma coleção

2021-07-01 00:19 UTC, rafael-g-depaulo commented on apps/client/src/Routes/AboutUs/AboutUsPage/styles.ts
> +  max-height: 400px;
recomendo botar um object-fit aqui. lembre que essas imagens vão ser inseridas por um usuário, e sempre temos que imaginar que a input do usuário vai ser a pior possível

2021-07-01 11:59 UTC, rafael-g-depaulo approved these changes
boa!

2021-07-01 12:04 UTC, merged