Feature/header banner#12
rafael-g-depaulo/labfaz pull request #37
Opened 2021-06-21 13:49 UTC by priscila-eng

Fixes branch, and add:
Header: layout mobile
Banner: props
client/.storyboook/preview.js: fixes theme provider

2021-06-21 17:34 UTC, rafael-g-depaulo requested changes
tudo tá ficando ótimo. código muito bem feito e organizado, como sempre. tem uns detalhes que eu acho bom mudar por questão de planejamento longo-prazo para evitar código duplicado no futuro e um detalhe da hitbox dos links da navbar, mas tá quase perfeito

2021-06-21 17:34 UTC, rafael-g-depaulo commented on apps/client/src/Components/Banner/style.ts
> +  height: ${props => props.height}rem;
De modo geral eu recomendo não usar height fixa (mesmo que recebendo ela como parâmetro). no lugar disso, deixar o próprio conteúdo interno do container (seus filhos e as margens deles), e o próprio padding do container determinarem dinamicamente a altura dele.

eu vou deixar pra vc decidir se vc refatora essa parte ou deixa assim, porque já tá bem implementado aqui e tá funcional nos tamanhos de tela que eu testei, mas no geral eu acho uma solução mais simples e segura contra bugs visuais não settar a height em situações como essa.

2021-06-21 17:34 UTC, rafael-g-depaulo commented on apps/client/src/Components/Banner/style.ts
> +  background-color: #C4C4C425;
Cores devem vir de váriaveis de css definidas em src/GlobalStyles (que podem ser reescrevidas localmente tbm).

exemplo de uso:
```typescript
  background-color: var(--background-gray);
  // onde existe um "--background-gray: #C4C4C425;" em src/GlobalStyles.ts
```

2021-06-21 17:34 UTC, rafael-g-depaulo commented on apps/client/src/Components/Banner/style.ts
> +  div {
Mesma coisa do comentário anterior sobre as variáveis de css. Tambem queria falar que esses h1 e h2 ficam melhor como componentes globais separado (um `<Title />` que receba um parâmetro dizendo se é h1 ou h2, ou dois componentes Title e Subtitle separados, sua escolha). O link também fica melhor como seu próprio styled component separado. em vez de estilizar todos os `<a>` dentro de `<Container />`, eu acho melhor criar um `<StyledLink />` estilizado por si só e só usar ele dentro do Container.

2021-06-21 17:34 UTC, rafael-g-depaulo commented on apps/client/src/Components/Banner/style.ts
> +    @media(max-width: 660px) {
Como eu demonstrei hoje de manhã na reunião, é bom usar a função de utilidade mobileOnly() aqui. exemplo:
```typescript
  ${mobileOnly(`
    padding: 0 2rem;
  `)}
```

2021-06-21 17:34 UTC, rafael-g-depaulo commented on apps/client/src/Components/Banner/index.tsx
> +        <h1> {title} </h1>
já comentei em Banner/style.ts, mas eu recomendo criar um componente global para títulos e estilizar ele, em vez de usar h1 e h2 padrão e usar estilização condicional de filhos em Container para estilizar eles

2021-06-21 17:34 UTC, rafael-g-depaulo commented on apps/client/src/Components/Header/Mobile/index.tsx
> +      <div className={open ? 'navBar active' : 'navBar'}>
aqui é bom usar a tag semântica de HTML <nav> em vez de div para representar uma barra de navegação

2021-06-21 17:34 UTC, rafael-g-depaulo commented on apps/client/src/Components/Header/Mobile/style.ts
> +    height: 100vh;
com o tamanho e posição atual do menu de navegação, se o conteúdo da página é maior que a tela tem como o usuário dar scroll pra baixo e escapar do menu. (um position sticky talvez resolva isso? eu não tenho certeza)
![image](https://user-images.githubusercontent.com/31452686/122802685-04ab5300-d29c-11eb-83c4-f99fa779f877.png)
![image](https://user-images.githubusercontent.com/31452686/122802705-0bd26100-d29c-11eb-927f-181402754101.png)

2021-06-21 17:34 UTC, rafael-g-depaulo commented on apps/client/src/Components/Header/Web/style.ts
> +      font-size: 12px;
esses media queries devem ser extraídos para uma lógica global externa (como o mobileOnly()). o tamanho da fonte e a cor devem ser variáveis css

2021-06-21 17:34 UTC, rafael-g-depaulo commented on apps/client/src/Components/Header/Web/style.ts
> +    flex-grow: 0.5;
o flex-grow funcionou muito bem para expandir horizontalmente a "hitbox" do link, mas verticalmente ainda não tá tão massa. eu testei localmente usar "padding: 0.6em 0;" em conjunção e ficou bom pra mim
![image](https://user-images.githubusercontent.com/31452686/122803739-61f3d400-d29d-11eb-97fc-7a5e868f8f6e.png)
![image](https://user-images.githubusercontent.com/31452686/122803757-6b7d3c00-d29d-11eb-9bfb-cb2d87e2a070.png)

(aqui sem o padding como exemplo)
![image](https://user-images.githubusercontent.com/31452686/122803776-7506a400-d29d-11eb-8a07-461c039b3e78.png)

2021-06-23 20:15 UTC, rafael-g-depaulo approved these changes
Absolutamente incrível. tudo certo!

2021-06-24 00:43 UTC, Jaxiii commented
Perfeito! 🚀

2021-06-24 14:42 UTC, merged