Feature/blog post card#28
rafael-g-depaulo/labfaz pull request #50
Opened 2021-06-30 12:27 UTC by clarice42

Implements #28

2021-07-01 00:36 UTC, rafael-g-depaulo requested changes
ótimo trabalho. alguns detalhes importantes pra refatorar, algumas mudanças opcionais que vc pode fazer se quiser (não precisa mesmo fazer aquele negócio do DateString que eu falei, foi só uma ideia pra vc manter em mente de uma ferramenta que o typescript te dá que pode ser útil no futuro)

2021-07-01 00:36 UTC, rafael-g-depaulo commented on apps/client/src/Api/BlogPost.ts
> +  image: any,
em 99,99% dos casos devemos evitar any como a praga. use Utils/Image para tipagem de imagens. exemplo de uso em Api/AboutUsBannerInfo

2021-07-01 00:36 UTC, rafael-g-depaulo commented on apps/client/src/Routes/Blog/BlogPage/PostCard/Display.tsx
> +                    <MainTextContainer>
componente *gigante* aqui. melhor dividir essa parte interna em componentes locais separados

2021-07-01 00:36 UTC, rafael-g-depaulo commented on apps/client/src/Routes/Blog/BlogPage/PostCard/Display.tsx
> +                    <MainTextContainer>
da linhas 38-59 e 60-78 são ótimos candidatos para refatoração em componentes menores

2021-07-01 00:36 UTC, rafael-g-depaulo commented on apps/client/src/Utils/formatPostDate.ts
> +function formatWeekDay(day: string) {
não precisa mudar nada aqui, mas uma ideia que eu tive que pode ser legal pensar em situações similares no futuro é definir um tipo união DateString e usar ele. exemplo:

```typescript
export type DateString = "Domingo" | "Segunda" | "Terça" | "Quarta" | "Quinta" | "Sexta" | "Sábado" | "Domingo"
export const formatWeekDay = (day: string): DateString => {}
```

2021-07-01 00:36 UTC, rafael-g-depaulo commented on apps/client/src/Utils/breakpoints/mobileOnly.ts
> +import { css, CSSProp } from "styled-components"
esse arquivo não deve existir mais. ele se tornou obsoleto quando eu reformatei a lógica dele em Util/breakpoints.ts. tem que remover ele, e todo uso de mobileOnly() deve ser trocado por Mobile()

2021-07-04 14:38 UTC, clarice42 commented on apps/client/src/Api/BlogPost.ts
> +  image: any,
Tem um problema com isso. Se eu usar a imagem com o tipo Image, e ela vier do strapi como null, vai dar erro porque ele só aceita o tipo Image.

2021-07-04 15:04 UTC, clarice42 commented on apps/client/src/Utils/formatPostDate.ts
> +function formatWeekDay(day: string) {
Eu incluí o tipo e fiz algumas mudanças de acordo com o padrão que o Seven colocou no layout

2021-07-04 15:08 UTC, clarice42 commented on apps/client/src/Routes/Blog/BlogPage/PostCard/Display.tsx
> +                    <MainTextContainer>
Eu dividi em dois arquivos diferentes; não achei que valia a pena criar pastas específicas porque ia repetir o arquivo de styles. Mas se achar melhor seguir o padrão, posso fazer isso.

2021-07-04 16:10 UTC, rafael-g-depaulo commented on apps/client/src/Api/BlogPost.ts
> +  image: any,
> Tem um problema com isso. Se eu usar a imagem com o tipo Image, e ela vier do strapi como null, vai dar erro porque ele só aceita o tipo Image.

então algo como `image?: Image`, `image: Image | null` deve ser uma boa solução

2021-07-04 16:23 UTC, rafael-g-depaulo commented on apps/client/src/Routes/Blog/BlogPage/PostCard/Display.tsx
> +                    <MainTextContainer>
ficou perfeito

2021-07-04 16:34 UTC, rafael-g-depaulo commented on apps/client/src/Routes/Blog/BlogPage/Display.tsx
> +  const { title, subtitle } = data!;
esse `data!` pode ser um `data` sem problema. eu recomendo evitar o uso do "!" quando possível

2021-07-04 16:48 UTC, rafael-g-depaulo requested changes

2021-07-04 16:48 UTC, rafael-g-depaulo commented on apps/client/src/Routes/Blog/BlogPage/PostCard/Mobile.tsx
> +        {image !== null ? (
eu acho que uma versão mais direta do que vc tá tentando dizer com esse código das linhas 38-42 seria:
```typescript
{ !!image &&  <Image src={image.url /* como testamos se image existe antes do && não precisa do "?."*/} alt={image.name} />}
```

2021-07-04 16:48 UTC, rafael-g-depaulo commented on apps/client/src/Routes/Blog/BlogPage/PostCard/Web.tsx
> +        {image !== null ? (
mesma coisa que eu falei no ./Mobile.tsx

2021-07-04 16:48 UTC, rafael-g-depaulo commented on apps/client/src/Routes/Blog/BlogPage/PostCard/styles.ts
> +  background-color: #000000;
cor deve vir de cssvars

2021-07-04 16:48 UTC, rafael-g-depaulo commented on apps/client/src/Routes/Blog/BlogPage/PostCard/styles.ts
> +  color: #ffffff;
cor deve vir de css-vars

2021-07-04 16:48 UTC, rafael-g-depaulo commented on apps/client/src/Routes/Blog/BlogPage/PostCard/styles.ts
> +  color: #ffffff;
cor deve vir de css-vars

2021-07-04 16:48 UTC, rafael-g-depaulo commented on apps/client/src/Routes/Blog/BlogPage/PostCard/styles.ts
> +  background-color: #fc0061;
cor deve vir de css-vars

2021-07-04 16:48 UTC, rafael-g-depaulo commented on apps/client/src/Routes/Blog/BlogPage/PostCard/styles.ts
> +  background-color: #ffec99;
cor deve vir de css-vars

2021-07-04 16:48 UTC, rafael-g-depaulo commented on apps/client/src/Routes/Blog/BlogPage/PostCard/styles.ts
> +  color: #ffec99;
eu acho que é melhor eu parar de comentar "cor deve vir de css-vars" e só deixar vc dar uma olhada no arquivo e fazer a substituição quando necessário

2021-07-04 16:48 UTC, rafael-g-depaulo commented on apps/client/src/Routes/Blog/BlogPage/PostCard/styles.ts
> +  text-transform: uppercase;
gostei do uso do text-transform: uppercase

2021-07-04 16:48 UTC, rafael-g-depaulo commented on apps/client/src/Routes/Blog/BlogPage/PostCard/styles.ts
> +  `)}
mandando um comentário adicional só pra falar que o css tá ótimo. a única coisa mesmo foi garantir que as cores vem de GlobalStyles, mas o css em si tá muito, muito bom.

2021-07-04 17:53 UTC, rafael-g-depaulo approved these changes

2021-07-10 16:07 UTC, rafael-g-depaulo requested changes
Adicionei stories para o PostCard que estava faltando. Agora é só refatorar pra usar InternalLinkButton, Typography/Text e Typography/Title dos componentes novos adicionados

2021-07-10 19:52 UTC, Jaxiii requested changes
Muito bom @clarice42! 
Só alguns pequenos detalhes que precisam ser acertados. 

O contraste do botão ( a parte amarela ao fundo) deve aparecer com 3px a esquerda e com 4px em cima.

Outra coisa seria o tamanho da fonte caso seja uma uma postagem de mais de 1 semana, ou seja, mostra o ano para o usuário, o mês e data ficam com tamanho 26px  (já esta certo na sua implementação), mas o ano em baixo fica com 32px. 
PS: Acho que eu fiz essa modificação depois de você assumir a Issue então minha culpa, peço desculpas.

<h4 align="center">Imagem Figma:</h4>

<p align="center">
  <img width="460" height="300" src="https://i.gyazo.com/b8b5c45f9a7af2dd53a0eff3fdb059ea.png">
</p>

<h4 align="center">Imagem Storybook:</h4>
<p align="center">
  <img width="460" height="300" src="https://i.imgur.com/AWPePw6.png">
</p>

<h4 align="center">Imagem Figma:</h4>

<p align="center">
  <img width="460" height="220" src="https://i.imgur.com/yG4DtN6.png">
</p>

<h4 align="center">Imagem Storybook:</h4>
<p align="center">
  <img width="460" height="300" src="https://i.imgur.com/en5kl69.png">
</p>

Mudanças muito pequeninas, mas retira um certa "estranheza" ao visualizar a página como um todo.

Trabalho excelente! Continue assim!!

2021-07-12 00:57 UTC, Jaxiii approved these changes
Nice!

2021-07-12 23:01 UTC, rafael-g-depaulo approved these changes
eu normalmente pediria pra mudar um detalhe de tipagem lá, mas como é uma coisinha só num componente local e não global eu não acho que vale a pena gastar o seu tempo resolvendo isso. issue completa! já vou juntar na develop

2021-07-12 23:28 UTC, closed without merging