Add UI in header e banner
rafael-g-depaulo/labfaz pull request #51
Opened 2021-06-30 16:00 UTC by priscila-eng

2021-07-04 17:01 UTC, rafael-g-depaulo approved these changes
No geral está ótimo, o único problema está na interatividade da UI. exemplo: o botão em vez de aparecer normalmente amarelo e usar um :hover e animar para o seu modo com a sombra preta, ele está permanentemente no estado hover

![image](https://user-images.githubusercontent.com/31452686/124393278-1515f180-dcd0-11eb-8929-a2034d4fe30b.png)
![image](https://user-images.githubusercontent.com/31452686/124393289-1c3cff80-dcd0-11eb-8be5-73e8f3338209.png)

Isso é, se eu interpretei de forma correta o que está no Figma. o @Jaxiii deve esclarecer qual o funcionamento correto do botão quando a interações do usuário e animação (hover, click, etc.).

eu vou aprovar porque tirando esse detalhe tá ótimo, e o Seven que tem autoridade pra dizer se esse é o funcionamento correto ou não.

2021-07-05 12:05 UTC, priscila-eng commented
> No geral está ótimo, o único problema está na interatividade da UI. exemplo: o botão em vez de aparecer normalmente amarelo e usar um :hover e animar para o seu modo com a sombra preta, ele está permanentemente no estado hover
> 
> ![image](https://user-images.githubusercontent.com/31452686/124393278-1515f180-dcd0-11eb-8929-a2034d4fe30b.png)
> ![image](https://user-images.githubusercontent.com/31452686/124393289-1c3cff80-dcd0-11eb-8be5-73e8f3338209.png)
> 
> Isso é, se eu interpretei de forma correta o que está no Figma. o @Jaxiii deve esclarecer qual o funcionamento correto do botão quando a interações do usuário e animação (hover, click, etc.).
> 
> eu vou aprovar porque tirando esse detalhe tá ótimo, e o Seven que tem autoridade pra dizer se esse é o funcionamento correto ou não.

Faz muito sentido isso!!

2021-07-08 20:05 UTC, Jaxiii requested changes
Massa Pri, tá muito bom! Mas eu to vendo aqui que o tamanho dos textos e dos componentes não estão com as medidas disponíveis no Figma. 

Os links do Header tem tamanho de texto 16 os botões são 175x39 em 1080.

Se você entrar no Figma pelo link: [https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components?node-id=0%3A1](https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components?node-id=0%3A1) você consegue clicar nos componentes e ver certinho o tamanho de cada componente!

2021-07-09 20:59 UTC, priscila-eng commented
@Jaxiii Eu tentei seguir exatamente os tamanhos do figma, mas pra telas maior que 1080 quando eu coloco o título 72px, fica muito grande na minha tela, então eu tento deixar proporcional com o que eu to vendo. Eu devo seguir o mesmo tamanho, mesmo que fique grande na minha tela?

2021-07-10 20:50 UTC, Jaxiii commented
> @Jaxiii Eu tentei seguir exatamente os tamanhos do Figma, mas para telas maiores que 1080 quando eu coloco o título 72px, fica muito grande na minha tela, então eu tento deixar proporcional com o que eu to vendo. Eu devo seguir o mesmo tamanho, mesmo que fique grande na minha tela?

@priscila-eng verdade, bem colocado.
As vezes algumas proporções não se refletem quando vamos implementa-las no código. Vamos tentar colocar o Titulo como 64px, o subtítulo como 22px e o texto do botão como 18px. ficaria mais ou menos assim:

<h4 align="center">Imagem Storybook com valores acima (menos o botão, não consegui editar) :</h4>

<p align="center">
  <img src="https://i.imgur.com/DErNnmH.png">
</p>

Outra coisa, quando eu mexo no tamanho do componente ele não altera entres os valores que deveriam corresponder a cada tamanho de componente. @rafael-g-depaulo.

<h4 align="center">Imagem Storybook  da responsividade:</h4>

<p align="center">
  <img src="https://i.imgur.com/oaJh2A9.png">
</p>

<h4 align="center">Imagem Storybook da responsividade:</h4>

<p align="center">
  <img src="https://i.imgur.com/mUtivqU.png">
</p>

<h4 align="center">Imagem Storybook  da responsividade:</h4>

<p align="center">
  <img src="https://i.imgur.com/GD6mUSo.png">
</p>

2021-07-10 22:13 UTC, priscila-eng commented
@Jaxiii vê se agora ficou bom, coloquei as mudanças que você falou do título, para os demais tamanhos de tela, segui a proporção, ex.: título era 72px para maiores de 1080, aí para 720px eu coloquei 54px e para mobile small coloquei 48px. O botão e o subtítulo, deixei os tamanhos do figma.

2021-07-12 00:25 UTC, Jaxiii requested changes
Massa @priscila-eng!

1. - [ ]  Tentar colocar o subtítulo em semi-bold. Acho que seria font-weight: 500.

2. - [ ]  **Só no Banner Mobile:** O Tamanho do banner esta mudando com o tamanho do texto, não teria como deixar ele fixo nos tamanhos do Figma? E colocar o padding ou margin para o botão? Seria ~360px de height pro small-mobile e ~414-420px pro normal-mobile. Os valores exatos não importam muito, mas a sim a proporção da distância do botão pros limites dos banner. A imagem pode dar uns valores/proporções referência.
  
3. - [X] O tamanho desse titulo [LABFAZ] não importa muito, muito provável que seja substituído por uma imagem logo. Mas desse jeito que você colocou agora ficou ótimo.
   
4. - [ ]  **Só no Header Mobile:** O tamanho do botão do menu tem que corresponder ao ícone, para poder centralizar no align. 
**PS**: O titulo LABFAZ tem possibilidade de ser substituído por uma imagem logo, que eu ainda não recebei então por enquanto vamos assumir que será com o texto

<h4 align="center">Imagem Storybook</h4>

<p align="center">
  <img src="https://i.imgur.com/1RLNAI0.png">
</p>

<h4 align="center">[ 2 ] - Imagem Storybook</h4>

<p align="center">
  <img src="https://i.imgur.com/xDBfTfb.png">
</p>

<h4 align="center">[ 2 ] - Imagem Referência do Figma</h4>

<p align="center">
  <img src="https://i.imgur.com/Q6ObncV.png">
</p>

<h4 align="center"> [ 4 ] - Imagem Storybook do Header Mobile</h4>

<p align="center">
  <img src="https://imgur.com/ds6FE9C.png">
</p>

<p align="center">
  <img src="https://i.imgur.com/buLBXl1.png">
</p>

<p align="center">
  <img src="https://i.imgur.com/spyyDP5.png">
</p>

<p align="center">
  <img src="https://i.imgur.com/9u6GoAh.png">
</p>

<p align="center">
  <img src="https://i.imgur.com/2TgyjYC.png">
</p>

<p align="center">
  <img src="https://i.imgur.com/oZnUn50.png">
</p>

2021-07-12 14:34 UTC, priscila-eng commented
@Jaxiii coloquei a logo como imagem, porque depois vai ser uma imagem e aí não precisa ficar alterando os testes.

2021-07-12 22:14 UTC, Jaxiii approved these changes
Muito bom @priscila-eng.

2021-07-13 13:28 UTC, merged