Feature/add staff to about us
rafael-g-depaulo/labfaz pull request #57
Opened 2021-07-01 22:30 UTC by Zipudhe

This PR create the Staff card component and add it to 'Quem Somos' page

#52

2021-07-10 19:23 UTC, rafael-g-depaulo requested changes
A cara final da seção de staff tá indo bem, mas tá com uma cara meio off ainda. Esse é o lugar do @Jaxiii definir, mas pra mim os elementos não estão encaixando direito, e a seção parece meio estranha e desconectada. Eu acho que é uma questão de mudar alguns paddings, margens e tamanhos de fonte por questão de alguns pixels. coisa de alguns detalhes pequenos pra fazer o todo "juntar" direito.

também tem umas coisas específica de código, que vem abaixo:

2021-07-10 19:23 UTC, rafael-g-depaulo commented on apps/client/src/GlobalStyles.tsx
> +  @import url('https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400&display=swap');
a gente tem uma linha em [public/index.html](https://github.com/rafael-g-depaulo/labfaz/blob/97780b951a428e5d91b05532932560b10240c417/apps/client/public/index.html#L18) e em [.storybook/preview.js](https://github.com/rafael-g-depaulo/labfaz/blob/97780b951a428e5d91b05532932560b10240c417/apps/client/.storybook/preview.js#L56) que já importam a fonte, então eu não acho que essa linha aqui seja necessária. rolou algum problema localmente que te levou a adicionar ela?

2021-07-10 19:23 UTC, rafael-g-depaulo commented on apps/client/src/Routes/AboutUs/AboutUsPage/Display.tsx
> +  const {banner_data, welcome_data, about_us_data} = about_data!
esse ! não é necessário aqui (devemos sempre tomar cuidado com "!", ele funciona de forma parecida com any, e pode esconder erros se usado sem o devido cuidado

2021-07-10 19:23 UTC, rafael-g-depaulo commented on apps/client/src/Routes/AboutUs/AboutUsPage/index.tsx
>  export const AboutUsPage: FC = () => {
a versão anterior desse arquivo (com `const result = useAboutUsdata()` em vez de `const { data, error, isLoading } = useAboutUsdata()`) usa melhor as type guard do typescript para saber se error e data são undefined ou não, e dessa forma a gente não precisa do "!" em data. eu recomendo fortemente voltar para a versão antiga

2021-07-10 19:23 UTC, rafael-g-depaulo commented on apps/client/src/Routes/AboutUs/AboutUsPage/StaffComponent/Staff.stories.tsx
> +storiesOf("Component/Staff", module)
tá Component em vez de Components, e isso faz com que ele caia em uma outra seção no Storybook, difernete dos outros componentes
![image](https://user-images.githubusercontent.com/31452686/125174181-e4373000-e199-11eb-972c-6b0c6de6a52a.png)

2021-07-12 22:07 UTC, rafael-g-depaulo requested changes
Alguns detalhes que precisam ser consertados, só. Quanto a parte visual da issue, vou deixar o Seven decidir se já tá legal ou não

2021-07-12 22:07 UTC, rafael-g-depaulo commented on apps/client/src/Routes/AboutUs/AboutUsPage/Display.tsx
> +      {data ? <Staff data={data} /> : <Loading /> }
lidar com data dessa forma não é muito ideal. o condicional com o Loading tá massa, mas não lida com o caso de erro. eu recomendo pegar const { data, error } em vez de só data, e ter um return cedo caso error exista (um <div>error: {error.message}</div> já basta por enquanto)

2021-07-13 16:13 UTC, Zipudhe commented
Fiz algumas alterações no estilo e proporção de alguns components, principalmente dos cards, acho que agora estão fazendo mais jus ao que está no figma

2021-07-13 21:44 UTC, Jaxiii requested changes
Massa @Zipudhe!

> Fiz algumas alterações no estilo e proporção de alguns components, principalmente dos cards, acho que agora estão fazendo mais jus ao que está no figma
 
Eu tirei as prints antes das suas alterações, então algumas coisas você já corrigiu.

Umas pequenas alterações são necessárias apenas:

1. - [x] Trocar a cor do titulo do componente geral staff de amarelo pra branco (ajuste depois de você assumir a issue, sorry)
2. - [x] Colocar o subtítulo "coordenacao" em uppercase.
3. - [x] Ajustar o padding (parte interna) do componente staff card para 1.28rem ( ~23px ) e remover a class ou o atributo que limita o texto interno. Para universalizar o tamanho livre dentro do componente para todos os subcomponentes internos. 
4. - [x] Colocar o circulo interno amarelo com background-image, que ira receber da API

<h4 align="center">[ 2 ]Imagem Storybook - Problema 2</h4>

![Imagem exemplo:](https://i.imgur.com/xbTLWen.png)

<h4 align="center">[ 3 ]Imagem Storybook - Problema 3</h4>

![Imagem exemplo:](https://i.imgur.com/HfCKdqw.png)
![Imagem exemplo:](https://i.imgur.com/2IOmmK5.png)
[![Image from Gyazo](https://i.gyazo.com/dd87790b9fccfa1f8a16e113e00ef6cc.gif)](https://gyazo.com/dd87790b9fccfa1f8a16e113e00ef6cc)

<h4 align="center">[ 4 ] Imagem Storybook - Problema 4</h4>

![Imagem exemplo:](https://i.imgur.com/2dIlLy0.png)

2021-07-14 02:35 UTC, Zipudhe commented
@Jaxiii Mudanças feitas!

2021-07-15 12:21 UTC, Jaxiii commented
> @Jaxiii Mudanças feitas!

Aqui o titulo "Staff" ainda esta amarelo, rola de botar em branco e em xx-large que acho que e 54px.

2021-07-16 20:18 UTC, Zipudhe commented
> > @Jaxiii Mudanças feitas!
> 
> Aqui o titulo "Staff" ainda esta amarelo, rola de botar em branco e em xx-large que acho que e 54px.

Feito!

2021-07-16 23:07 UTC, Jaxiii approved these changes
Nice @Zipudhe!

@rafael-g-depaulo por mim está aprovado, depois eu tenho que ver a composição geral das paginas pra pedir algumas alterações pontuais, mas para isso eu abro um novo issue no futuro.

2021-07-19 19:29 UTC, rafael-g-depaulo approved these changes
ótimo trabalho! já vou dar o merge aqui

2021-07-19 19:29 UTC, rafael-g-depaulo commented on apps/client/src/Routes/AboutUs/AboutUsPage/StaffComponent/index.tsx
> +        <Title level={3} > Lorem ipsum dolor sit amet, consectetur adipiscing elit.  </Title>
eu vou deixar passar pq a gente não tá vendendo módulo de acessibilidade (a11y) nesse projeto, mas pular níveis de título do h1 direto pro h3 é um antipadrão e quebra uma regra bem clara de a11y. bom lembrar para projetos futuros

2021-07-19 19:32 UTC, merged