🚧 Create files for construction page
rafael-g-depaulo/labfaz pull request #59
Opened 2021-07-02 14:26 UTC by priscila-eng

Add Construction Page

2021-07-09 02:47 UTC, rafael-g-depaulo requested changes
Tá muito, muito, muito bom. só mudar o negócio dos links das redes sociais e eu já junto com a develop

2021-07-09 02:47 UTC, rafael-g-depaulo commented on apps/client/src/Pages/Contruction/index.tsx
> +  if(width) return <Mobile data={result.data!}/>
não precisava do ! aqui, porque como não separamos o "result" em variáveis diferentes o próprio typescript reconhece que data aqui não é undefined por causa dos ifs anteriores. poder evitar usar "!" (que é como any, uma arma perigosa de se usar) é na verdade o motivo principal de termos refatorado o código antigo para usar result em vez de `{ data, isLoading, error }`

2021-07-09 02:47 UTC, rafael-g-depaulo commented on apps/client/src/Pages/Contruction/Header/index.tsx
> +  const {facebook, twitter, linkedin, googlePlus} = data!
também não precisa do ! aqui. nesse caso, porque o tipo das props (data: SocialNetworksLabfaz, em vez de uma data?: SocialNetworksLabfaz) nos garante que data não vai ser undefined, então esse ! não está fazendo nada

2021-07-09 02:47 UTC, rafael-g-depaulo commented on apps/client/src/Pages/Contruction/Header/index.tsx
> +
eu tive uma ideia. eu tenho certeza que o projeto não tem google+, e ele muito provavelmente não tem um linkedin. isso me leva a pensar que seria legal a gente assumir que os links que a gente recebe do strapi podem estar vazios (ou seja, que a equipe de comunicação não botou nada porque essa conta de rede social ainda não existe ou não vai existir. como no caso do google+), e fazer um teste lá em baixo no render, tipo:
```tsx
{ !!googlePlus && googlePlus !== "" && /* esse link só renderiza se o link do googleplus for uma string não nula*/
  <Icon>
    <FaGooglePlusSquare />
  </Icon>
}
```

2021-07-09 02:47 UTC, rafael-g-depaulo commented on apps/client/src/Pages/Contruction/Header/index.tsx
> +
ah, e vai precisar de um pro instagram, com certeza. esse é de longe a rede social mais importante do projeto

2021-07-09 14:24 UTC, priscila-eng commented on apps/client/src/Pages/Contruction/Header/index.tsx
> +
Adicionei, usei o botão global, mas ele não tem target="_blank", eu tentei colocar onde eu estou chamando, mas ele não aceita. Então, quando eu clico no link ele redireciona e abre na mesma aba do site, ao invés de abrir em uma aba separada. Tudo bem ser assim?

2021-07-10 20:05 UTC, rafael-g-depaulo requested changes
tá tudo ótimo, Pri. mais uma coisinha só e juto que termina!

2021-07-10 20:05 UTC, rafael-g-depaulo commented on apps/client/src/Pages/Contruction/Header/index.tsx
> +
é bom a gente mudar o próprio botão global e adicionar o target="_blank" rel="noopener" direto pra ele, já que é o comportamento padrão que queremos para todos os links. vc pode fazer essa mudança no botão global?

2021-07-10 20:05 UTC, rafael-g-depaulo commented on apps/client/src/Pages/Contruction/Header/index.tsx
> +
e só pra ficar melhor pro usuário responsável por criação de conteúdo eu acho que é bom a gente adicionar o mesmo teste nos links das outras redes sociais, tbm pra ficar mais padronizado

2021-07-10 21:19 UTC, priscila-eng commented on apps/client/src/Pages/Contruction/Header/index.tsx
> +
Tá bom, posso sim!! Vou adicionar

2021-07-10 22:57 UTC, rafael-g-depaulo approved these changes

2021-07-10 23:00 UTC, merged