Feature/courses presentation UI#19
rafael-g-depaulo/labfaz pull request #63
Opened 2021-07-08 01:19 UTC by clarice42

Fix #19

2021-07-20 17:48 UTC, rafael-g-depaulo approved these changes
tem alguns pequenos detalhes que não estão perfeitos, mas no geral tá incrível! por mim já passou nos critérios, dá pra juntar no resto da codebase na develop

2021-07-20 17:48 UTC, rafael-g-depaulo commented on apps/client/src/Components/CoursesPresentation/Card/styles.ts
>    grid-template-areas:
eu acho que daria pra implementar esse caso usando uma grid 2x2 e grid-gap, não? tá ótimo do jeito que tá, eu só acho que talvez seria mais fácil usando grip-gap em vez de espaços vazios na grid

2021-07-20 17:48 UTC, rafael-g-depaulo commented on apps/client/src/Utils/useMobile.ts
> +  return screenWidth < desktopSmall
ótima mudança! esse era um erro antigo que tínhamos deixado passar antes. mandou bem corrigindo isso aqui

2021-07-21 15:26 UTC, rafael-g-depaulo requested changes

2021-07-21 15:26 UTC, rafael-g-depaulo commented on apps/client/src/Components/Header/Web/style.ts
> +      font-size: var(--font-size-short: 11px);
mesma coisa que eu falei no comentário anterior

2021-07-22 02:08 UTC, rafael-g-depaulo approved these changes

2021-07-27 11:57 UTC, Jaxiii approved these changes
@clarice42 Excelente Clara, muito bom mesmo!

@rafael-g-depaulo vou aprovar, pois as pequenas coisas que eu vi que precisam ser alteradas também são coisas que a coordenação pediu alteração, então vou evitar o retrabalho inútil até termos uma palavra final da coordenação e incluir no issue de mudanças da UI que falamos na reunião de ontem quando a palavra final for tomada.

2021-07-28 23:32 UTC, merged