🎨 Change component structure
rafael-g-depaulo/labfaz pull request #71
Opened 2021-07-12 12:54 UTC by priscila-eng

Improve and update loading component for square loader

2021-07-13 12:22 UTC, priscila-eng commented
@Jaxiii eu deixo o background preto ou branco mesmo?

2021-07-13 13:25 UTC, rafael-g-depaulo commented
> @Jaxiii eu deixo o background preto ou branco mesmo?

eu acho bom deixar o background transparente, para que funcione bem em qualquer ambiente que for usado

2021-07-20 03:30 UTC, rafael-g-depaulo requested changes
tá muito bom, a cara dele ficou incrível. mas tem um detalhe que eu notei que pode virar um problema em alguns use-cases do componente

2021-07-20 03:30 UTC, rafael-g-depaulo commented on apps/client/src/Components/Loading/style.ts
> +  width: 100vw;
o componente de loading vai ser usado em vários contextos, e em alguns deles ele não vai tomar a tela toda (na página de "sobre nós", por exemplo, a listagem da staff é carregada assincronamente e enquanto estiver carregando a área onde a lista de staff ficaria vai ter o componente de loading).

por isso, width: 100vw e height: 100vh não funcionam aqui. width: 100% e height: 100% deve ficar melhor.

2021-07-20 17:24 UTC, rafael-g-depaulo commented on apps/client/src/Components/Loading/style.ts
> +  width: 100vw;
uma ideia de teste desse caso de uso é criar uma story no storybook com o componente de load como filho de um div com tamanho fixo (e com uma borda, só pra gente poder visualizar os limites e tamanho do container)

2021-07-21 18:21 UTC, rafael-g-depaulo approved these changes

2021-07-21 18:26 UTC, merged