🚧  Implements not found page
rafael-g-depaulo/labfaz pull request #72
Opened 2021-07-13 16:24 UTC by priscila-eng

Implements Not Found page and improve

2021-07-20 17:59 UTC, rafael-g-depaulo approved these changes
Ótimo! nenhum comentário, 110% aprovado.

mentira, 1 comentário: gostei bastante do seu uso de unidades. eu não sou um expert nisso, mas eu acredito que vc usou as unidades corretas para a situação

2021-07-27 12:12 UTC, Jaxiii requested changes
@priscila-eng na minha tela (1920x1080) o componente não esta centralizando. O resto esta 100%, muito bom! 

![](https://i.imgur.com/g2W7n7m.png)

2021-07-27 21:55 UTC, priscila-eng commented
Prontinho @Jaxiii já ajustei

2021-07-29 00:31 UTC, Jaxiii approved these changes
Nice!

2021-07-29 13:10 UTC, closed without merging