🚧 Add footer component
rafael-g-depaulo/labfaz pull request #75
Opened 2021-07-19 11:20 UTC by priscila-eng

Improve old footer and add UI

2021-07-26 18:38 UTC, rafael-g-depaulo approved these changes

2021-07-27 17:46 UTC, Jaxiii requested changes
@priscila-eng Muito bom, vou pedir só umas mudanças pequenas e todas apenas de margin, tamanho e alinhamento. 

**OBS: Item 1 e 2, apenas para o web-normal 1080p, no web-small 720p essas modificações não são necessárias, apenas alinhamento.

1. - [x] Aumentar o tamanho ou colocar uma margem no Footer para distanciar os componentes das bordas do Footer. **ver distancia na penúltima imagem*
2. - [x] Aumentar as margens nos hyperlinks de navegação em 1080p
3. - [x] Aumentar as margens nos contatos de fale com a gente para alinhar com o input do email. **ver linha guia na ultima imagem**
4. - [x] Alinhar o titulo de navegação com os outros títulos. **ver linha guia na ultima imagem**

A estranheza de proporção entre o 720p e 1080p eu acho que é porque a fonte aumenta mas o tamanha do Height do Footer não, por isso a modificação [1]

<h4 align="center">Storybook 1080p</h4>

![](https://i.imgur.com/47bg82C.png)

<h4 align="center">Storybook 720p</h4>
![](https://imgur.com/HIQwuHx.png)

<h4 align="center">Figma - Distancia do componente ate as margens - 1080p</h4>

![](https://i.imgur.com/gNzTMyW.png)

<h4 align="center">Figma -  Linhas Guias Adicionadas</h4>

![](https://i.imgur.com/2fVSXcb.png)

2021-07-28 00:12 UTC, priscila-eng commented
@Jaxiii acho que consertei tudo

2021-07-29 00:24 UTC, Jaxiii approved these changes
Lindo, aprovado!

2021-07-29 13:09 UTC, merged