📱 ✨ feaure drawer component with stories
rafael-g-depaulo/labfaz pull request #91
Opened 2021-08-10 18:09 UTC by Zipudhe

Refactor staff component to match UI design

2021-08-15 21:54 UTC, rafael-g-depaulo requested changes
Por questão de UX, acho melhor deixar que qualquer click no Drawer collapsado funcione pra dar toggle nele, não só no ícone. De resto tá muito bom

![image](https://user-images.githubusercontent.com/31452686/129493906-627c745d-c0a3-4dc3-ad4e-39ee80277b31.png)

2021-08-17 02:18 UTC, Zipudhe commented
> Por questão de UX, acho melhor deixar que qualquer click no Drawer collapsado funcione pra dar toggle nele, não só no ícone. De resto tá muito bom
> 
> ![image](https://user-images.githubusercontent.com/31452686/129493906-627c745d-c0a3-4dc3-ad4e-39ee80277b31.png)

resolvido!

2021-08-17 14:35 UTC, rafael-g-depaulo requested changes
![image](https://user-images.githubusercontent.com/31452686/129745837-92be8883-b288-4419-b930-83265087d27f.png)
![image](https://user-images.githubusercontent.com/31452686/129745876-3a5c79b2-3713-4df5-9770-825d9b448344.png)
![image](https://user-images.githubusercontent.com/31452686/129745891-a983e5a1-296b-4937-9dc7-5a5eef7fef20.png)

o funcionamento tá ótimo, mas é melhor deixar cursor: pointer em tudo, não só na seta, pra comunicar para o usuário que é uma área clicável

2021-08-17 22:43 UTC, rafael-g-depaulo approved these changes

2021-08-18 00:16 UTC, rafael-g-depaulo approved these changes
por mim tá ótimo, só esperar pela resposta do @Jaxiii e dou merge

2021-08-19 21:33 UTC, rafael-g-depaulo commented
a Wemmia e a Moara vão começar a inserir a equipe no strapi por agora, então eu já vou fazer o merge agora e se precisar alterar algo a gente cria uma issue nova

2021-08-19 21:52 UTC, merged